kpfind will now grep over current namespace by default. Add -a flag to search all namespaces.

diff --git a/bin/kpfind b/bin/kpfind
--- a/bin/kpfind
+++ b/bin/kpfind
@@ -2,5 +2,32 @@
 
 # Search pods using regular expression
 
-column -t <<< $(kubectl get pods --all-namespaces -o wide | \
-  kpfind.awk -v regex="${1}")
+# TODO
+function usage {
+  echo "Usage: kpfind [a] regex"
+  echo "Regex search pods in namespace(s)."
+}
+
+
+while getopts "a:?h" opt; do
+  case $opt in
+    a)
+      regex=$OPTARG
+      ;;
+    h|\?)
+      # echo "Invalid option: -$OPTARG" >&2
+      usage
+      exit 0
+      ;;
+  esac
+done
+
+
+if [ -n "${regex}" ]
+then
+  column -t <<< $(kubectl get pods --all-namespaces -o wide | \
+    kpfind.awk -v regex="${regex}")
+else
+  column -t <<< $(kubectl get pods -o wide | kpfind.awk -v regex="${1}")
+fi
+
